services:
  api:
    build: 
      context: fastapi-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-server:/app
    env_file: 
      - ./fastapi-server/.env
    environment:
      - PYTHONPATH=/app
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ./fastapi-server/.env
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data:

  
  # Example database service if needed:
  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=app

# volumes:
#   postgres_data: