version: '3.8'

services:
  api:
    build: 
      context: fastapi-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-server:/app
    env_file: 
      - ./fastapi-server/.env
    environment:
      - PYTHONPATH=/app
    restart: always
    # If you need to connect to other services like a database,
    # you can add them here and define them as separate services below
    # depends_on:
    #   - db
  
  # Example database service if needed:
  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=app

# volumes:
#   postgres_data: