import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
	FpjsProvider,
	FingerprintJSPro,
} from "@fingerprintjs/fingerprintjs-pro-react";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<FpjsProvider
					loadOptions={{
						apiKey: process.env.NEXT_PUBLIC_FPJS_API_KEY || "",
						endpoint: [FingerprintJSPro.defaultEndpoint],
						scriptUrlPattern: [
							FingerprintJSPro.defaultScriptUrlPattern,
						],
						region: "eu",
					}}
				>
					{children}
				</FpjsProvider>
			</body>
		</html>
	);
}
